In [1]:
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('training_data_2_csv_UTF.csv',encoding = "ISO-8859-1")
df.head(4)

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,created_at,favourites_count,verified,statuses_count,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot
0,8.160000e+17,"""815745789754417152""","""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokÅ½mon in Houston, TX. See ...","""https://t.co/dnWuDbFRkt""",1291,0,10,"""Mon Jan 02 02:25:26 +0000 2017""",0,False,78554,"""en""","{\r ""created_at"": ""Sun Mar 12 15:44:04 +0...",True,False,False,"""Houston PokÅ½ Alert""",1
1,4.843621e+09,4843621225,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,NaN,1,349,0,2/1/2016 7:37,38,False,31,en,null,True,False,False,Keri Nelson,1
2,4.303727e+09,4303727112,mattlieberisbot,NaN,"Inspired by the smart, funny folks at @replyal...",https://t.co/P1e1o0m4KC,1086,0,14,Fri Nov 20 18:53:22 +0000 2015,0,False,713,en,"{'retweeted': False, 'is_quote_status': False,...",True,False,False,Matt Lieber Is Bot,1
3,3.063139e+09,3063139353,sc_papers,NaN,NaN,NaN,33,0,8,2/25/2015 20:11,0,False,676,en,Construction of human anti-tetanus single-chai...,True,True,False,single cell papers,1

In [2]:
j=0
for i in df.index:    
        if 'bot' in str(df.loc[i,'description'])or 'Bot' in str(df.loc[i,'description']) or 'b0t' in str(df.loc[i,'description']) or 'BOT' in str(df.loc[i,'description']) or 'B0T' in str(df.loc[i,'description']) or 'boT' in str(df.loc[i,'description']):
            
            df.loc[i,'flag1'] = True
            j=j+1
        else:
            df.loc[i,'flag1'] = False
print(j)

409

In [3]:
j=0
for i in df.index:    
        if 'bot' in str(df.loc[i,'screen_name'])or 'Bot' in str(df.loc[i,'screen_name']) or 'b0t' in str(df.loc[i,'screen_name']) or 'BOT' in str(df.loc[i,'screen_name']) or 'B0T' in str(df.loc[i,'screen_name']) or 'boT' in str(df.loc[i,'screen_name']):
            
            df.loc[i,'flag2'] = True
            j=j+1
        else:
            df.loc[i,'flag2'] = False
print(j)

232

In [4]:
j=0
for i in df.index:    
        if 'bot' in str(df.loc[i,'name'])or 'Bot' in str(df.loc[i,'name']) or 'b0t' in str(df.loc[i,'name']) or 'BOT' in str(df.loc[i,'name']) or 'B0T' in str(df.loc[i,'name']) or 'boT' in str(df.loc[i,'name']):
            
            df.loc[i,'flag3'] = True
            j=j+1
        else:
            df.loc[i,'flag3'] = False
print(j)

198

In [5]:
df.head(5)

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,created_at,...,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot,flag1,flag2,flag3
0,8.160000e+17,"""815745789754417152""","""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokÅ½mon in Houston, TX. See ...","""https://t.co/dnWuDbFRkt""",1291,0,10,"""Mon Jan 02 02:25:26 +0000 2017""",...,"""en""","{\r ""created_at"": ""Sun Mar 12 15:44:04 +0...",True,False,False,"""Houston PokÅ½ Alert""",1,False,False,False
1,4.843621e+09,4843621225,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,NaN,1,349,0,2/1/2016 7:37,...,en,null,True,False,False,Keri Nelson,1,False,False,False
2,4.303727e+09,4303727112,mattlieberisbot,NaN,"Inspired by the smart, funny folks at @replyal...",https://t.co/P1e1o0m4KC,1086,0,14,Fri Nov 20 18:53:22 +0000 2015,...,en,"{'retweeted': False, 'is_quote_status': False,...",True,False,False,Matt Lieber Is Bot,1,True,True,True
3,3.063139e+09,3063139353,sc_papers,NaN,NaN,NaN,33,0,8,2/25/2015 20:11,...,en,Construction of human anti-tetanus single-chai...,True,True,False,single cell papers,1,False,False,False
4,2.955142e+09,2955142070,lucarivera16,"Dublin, United States",Inspiring cooks everywhere since 1956.,NaN,11,745,0,1/1/2015 17:44,...,en,null,False,False,False,lucarivera16,1,False,False,False

In [6]:
# df['has_extended_profile']=df['has_extended_profile'].fillna(False)
# df['default_profile_image']=df['default_profile_image'].fillna(False)

In [6]:
features = [df.columns[6],df.columns[7],df.columns[12],df.columns[20],df.columns[21],df.columns[22]]
def test1():
    df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
    train, test = df[df['is_train']==True], df[df['is_train']==False]
    #print('Number of observations in the training data:', len(train))
    #print('Number of observations in the test data:',len(test))
    y=train['bot']
    clf = RandomForestClassifier(n_jobs=2)
    clf.fit(train[features], y)
    pred=clf.predict(test[features])
    return (np.mean(pred==test['bot']))

In [7]:
sum(test1() for _ in range(10))/10.0

0.87921584534503094

In [19]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
train, test = df[df['is_train']==True], df[df['is_train']==False]
# print('Number of observations in the training data:', len(train))
# print('Number of observations in the test data:',len(test))

In [9]:
features = [df.columns[6],df.columns[7],df.columns[11],df.columns[12],df.columns[20],df.columns[21],df.columns[22]]

features

['followers_count',
 'friends_count',
 'verified',
 'statuses_count',
 'flag1',
 'flag2',
 'flag3']

In [10]:
y=train['bot']

In [15]:
clf = RandomForestClassifier(n_jobs=2)
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [20]:
pred=clf.predict(test[features])
print (np.mean(pred==test['bot']))

0.964673913043

In [17]:
# clf.predict_proba(test[features])

In [18]:
list(zip(train[features], clf.feature_importances_))

[('followers_count', 0.25670853050943554),
 ('friends_count', 0.3664394591003215),
 ('verified', 0.1209383980011173),
 ('statuses_count', 0.14882579955097711),
 ('flag1', 0.077340235851785372),
 ('flag2', 0.017076945580206011),
 ('flag3', 0.012670631406157132)]

numpy.bool_

In [17]:
# features_tree=[df.columns[6],df.columns[7],df.columns[10],df.columns[12],df.columns[11],df.columns[15],df.columns[16]]
# features_tree
# clftree = tree.DecisionTreeClassifier()
# clftree = clftree.fit(train[features_tree], y)
# clftree.predict(test[features_tree])
# predtree=clftree.predict(test[features_tree])
# print (np.mean(predtree==test['bot']))

In [44]:
# print(len(test))
# j=0
# changed =0
# for i in test['screen_name']:
#     if 'bot' in i or 'Bot' in i or 'b0t' in i or 'BOT' in i:
#         if pred[j]!=1:
#             pred[j]=1
            
#             print(j)
#             changed=changed+1
#         j=j+1
# print (np.mean(pred==test['bot']))
# print(changed)
# print(type(pred[1]))

790
21
23
24
25
50
53
54
59
0.912658227848
8
<class 'numpy.int64'>

In [45]:
# print(len(test))
# j=0
# changed =0
# for i in test['description']:
#      if 'bot' in str(i) or 'Bot' in str(i) or 'b0t' in str(i):
#         if pred[j]!=1:
#             pred[j]=1
            
#             print(j)
#             changed=changed+1
#         j=j+1
# print (np.mean(pred==test['bot']))
# print(changed)

790
68
84
90
0.916455696203
3

In [15]:
# j=0
# for i in test['description']: 
#     if type(i)==float:
#         i=str(i)
#     #print(pred[j])
#     #print(type(i))
#     j=j+1

In [277]:
# df['default_profile'].describe()

In [22]:
df_test = pd.read_csv('test_data_4_students.csv',encoding = "UTF").dropna(how='all')
df_test.head(20)

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listed_count,created_at,favorites_count,verified,statuses_count,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot
0,2.281293e+09,2281292622,__keating,brooklyn,lgbt editor at @buzzfeed. shannon.keating@buzz...,https://t.co/QneJmYRyhj,4466,1295,111,Tue Jan 07 23:26:52 +0000 2014,1579,TRUE,3036.0,en,{'created_at': 'Tue Apr 11 15:31:51 +0000 2017...,FALSE,FALSE,FALSE,shannon keating,NaN
1,2.344040e+09,2344040251,_callme_Dani,"Los Angeles, CA",News Curation Editor @BuzzFeedNews \rI do a lo...,NaN,295,1016,10,Fri Feb 14 19:45:56 +0000 2014,300,FALSE,618.0,en,{'created_at': 'Tue Apr 11 00:56:02 +0000 2017...,FALSE,FALSE,FALSE,Danielle Hopkins,NaN
2,7.658713e+08,765871267,_little_britt_,NaN,Family comes first! Also I am in love with piz...,https://t.co/E7DE1cJB7e,1001678,3017,14,8/18/2012 15:13,13040,TRUE,3329.0,en,"{'place': None, 'retweeted': False, 'favorited...",TRUE,FALSE,TRUE,Brittney Smith,NaN
3,4.772373e+09,4772373433,134k5,NaN,@BuzzFeedJapan ‰  @cnet_japan / DMŽÐÜ‹ã‹_‹...,https://t.co/Cbguzs2PjT,445,487,17,Sun Jan 17 07:11:45 +0000 2016,1112,FALSE,46.0,ja,{'created_at': 'Sat Apr 08 08:41:08 +0000 2017...,FALSE,FALSE,TRUE,Keigo Isashi,NaN
4,1.324549e+09,None,2181chrom_bot,è‡ªåˆ†ã®å¤©å¹•,ã“ã‚Œã¯FEè¦šé†’ã®ã‚¯ãƒ­ãƒ â€¦ã¤ã¾ã‚Šä¿ºã...,http://t.co/10Swf6luED,187,68,13,Wed Apr 03 13:00:42 +0000 2013,None,None,690359.0,ja,"{u'lang': u'ja', u'text': u'@2181lucina_bot \u...",None,None,None,ãƒ„ã‚¤å»ƒã‚¯ãƒ­ãƒ bot,NaN
5,2.561342e+09,None,2LA1R_bot,None,ãµã‚Œã‚èªžã‚’ã¤ã¶ã‚„ãbotã§ã™ ãŸã¾ã«...,None,80,87,None,Wed Jun 11 13:12:06 +0000 2014,None,None,20167.0,ja,"{u'lang': u'ja', u'text': u'\u3010\u3075\u308c...",TRUE,None,None,ãµã‚Œã‚èªžbot ver0.2,NaN
6,3.478101e+08,None,3pei_bot,ä¸‰æ²³å±‹,â– ã¡ã‚ãƒ¼ã™ï¼ä¸‰æ²³å±‹ã§ãƒ¼ã™ï¼ä¸‰éƒŽã...,http://twpf.jp/3pei_bot,2020,1978,56,Wed Aug 03 11:52:59 +0000 2011,None,None,968182.0,ja,"{u'lang': u'ja', u'text': u'@kazenoraby \uff66...",TRUE,None,None,ä¸‰æ²³å±‹ä¸‰å¹³,NaN
7,8.563039e+08,None,94kichi_bot,None,94 ãƒãƒ£ãƒƒã‚¯ãƒ»ã‚¦ã‚£ãƒ«ã‚½ãƒ³ã¨æ„‰å¿«ãªä...,None,70,80,2,Mon Oct 01 12:39:46 +0000 2012,None,None,76735.0,ja,"{u'lang': u'ja', u'text': u'\u307f\u3093\u306a...",TRUE,None,None,94å¹´çµ„bot,NaN
8,8.328750e+17,None,A3_Dekasegi_bot,ãƒ“ãƒ­ãƒ¼ãƒ‰é§…å‰,ã‚·ãƒˆãƒ­ãƒ³ã€ŒA3!å‡ºç¨¼ãŽæ—¥èªŒãƒ€ãƒ¨ãƒ¼ï¼ã...,https://t.co/t171JmIrjL,181,144,2,Sat Feb 18 08:50:03 +0000 2017,None,None,1960.0,ja,"{u'lang': u'ja', u'text': u'\u30b7\u30c8\u30ed...",TRUE,None,None,A3! å‡ºç¨¼ãŽæ—¥èªŒ,NaN
9,8.885679e+07,None,aamir_khan,Mumbai,Actor.,https://t.co/l1dUhQjS8Y,20419393,9,6,Tue Nov 10 05:08:56 +0000 2009,None,TRUE,468.0,en,"{u'lang': u'en', u'text': u'Hey guys, doing so...",None,None,None,Aamir Khan,NaN
10,7.135570e+17,7.14E+17,AceWallpaperBot,NaN,Posts a [SFW] wallpaper every 30 minutes. Ever...,https://t.co/tuq9iPhc0Z,20423,8,130,3/26/2016 2:42,0,FALSE,17387.0,en,"{'favorite_count': 12, 'id': 85143235585630617...",FALSE,FALSE,FALSE,AceWallpaperBot,NaN
11,1.566747e+09,1566746503,acormier_bzfd,"New York, NY",Investigative Reporter-Editor @buzzfeed. Forme...,https://t.co/iiAufe34NG,1436,2017,55,Wed Jul 03 21:28:01 +0000 2013,1099,TRUE,967.0,en,{'created_at': 'Tue Apr 11 14:07:03 +0000 2017...,FALSE,FALSE,TRUE,Anthony Cormier,NaN
12,9.042031e+07,None,ActuallyNPH,Manhattanland,"I dig variety acts, Pixar, puppets, prestidigi...",https://t.co/c8ibVF0Lfq,26376073,91,60767,Mon Nov 16 15:54:48 +0000 2009,None,TRUE,2666.0,en,"{u'lang': u'en', u'text': u""Podcast recommenda...",None,None,None,Neil Patrick Harris,NaN
13,1.849100e+08,None,Adele,London,https://t.co/5Vf55N5xFe,https://t.co/5Vf55N5xFe,27950120,157,32993,Mon Aug 30 19:53:19 +0000 2010,None,TRUE,287.0,en,"{u'lang': u'en', u'truncated': True, u'text': ...",None,None,None,Adele,NaN
14,1.576906e+08,157690631,aflores,Los Angeles,Latino affairs and breaking news reporter for ...,http://t.co/ykLlu4DCdC,5210,2555,232,Sun Jun 20 15:27:55 +0000 2010,1169,TRUE,5501.0,en,{'created_at': 'Tue Apr 11 18:31:46 +0000 2017...,FALSE,FALSE,FALSE,Adolfo Flores,NaN
15,4.242035e+07,None,agnezmo,Los Angeles,DREAM BELIEVE & MAKE IT HAPPEN! Instagram: @ag...,https://t.co/PYhVmN5FYH,16328463,1071,10848,Mon May 25 15:05:00 +0000 2009,None,TRUE,14596.0,en,"{u'lang': u'en', u'text': u'Too comfortable \U...",None,None,None,AGNEZ MO,NaN
16,4.238245e+07,42382447,Agostinozoida,NaN,NaN,https://t.co/2gdWyQjNq4,964,331,15,5/25/2009 10:02,2832,FALSE,6389.0,en,"{'place': None, 'retweeted_status': {'place': ...",FALSE,FALSE,TRUE,laughkommander,NaN
17,4.399328e+07,43993280,AhmedBharoocha,NaN,I forget to tweet,https://t.co/iM3lj0uBHg,5254,2407,102,6/1/2009 22:44,3082,FALSE,3392.0,en,"{'place': None, 'retweeted_status': {'place': ...",TRUE,FALSE,TRUE,Ahmed Bharoocha,NaN
18,2.305237e+09,None,aho_levi_bot,teamãƒªãƒ´ã‚¡ã‚¤,YDKã€‚botã‚·ã‚¹ãƒ†ãƒ å¤–éƒ¨ãƒ¬ãƒ³ã‚¿ãƒ«ã‹ã‚‰è...,None,446,431,4,Wed Jan 22 17:52:19 +0000 2014,None,None,119680.0,ja,"{u'lang': u'ja', u'text': u'@kotsubu_149 \u306...",None,None,None,é€²æ’ƒã®ãŠãƒã‚«ã•ã‚“(Ïƒâ–½Ïƒ),NaN
19,7.427940e+17,7.43E+17,aiomacbot,NaN,A simple all-in-one bot for the Mac,https://t.co/cR0QCvj4cu,1404,0,2,6/14/2016 18:59,12,FALSE,141.0,en,"{'favorite_count': 2, 'id': 851175528384081922...",TRUE,FALSE,FALSE,TaskBot,NaN

In [6]:
df_test['id'][539]

7.28e+17

In [23]:
newf=['followers_count',
 'friends_count',
      "verified",
 'statuses_count',
      
     'flag1','flag2'
      
     ,'flag3']

In [280]:

# def change(x):
#     if 'None' in x:
#         return median(x)
#     else:
#         return x
# df_test['listed_count']=df_test['listed_count'].map(change)
# df_test['favorites_count']=df_test['favorites_count'].map(change)
# #df_test['statuses_count']=df_test['statuses_count'].map(change)
# df_test['followers_count']=df_test['followers_count'].map(change)
# df_test['friends_count']=df_test['friends_count'].map(change)

In [13]:
# df_test['listed_count'] = pd.to_numeric(df_test['listed_count'],errors='coerce')

# df_test['listed_count'] = df_test['listed_count'].fillna(df_test['listed_count'].median())

In [12]:
# df_test['favorites_count'] = pd.to_numeric(df_test['favorites_count'],errors='coerce')

# df_test['favorites_count'] = df_test['favorites_count'].fillna(df_test['favorites_count'].median())

In [24]:
df_test['followers_count'] = pd.to_numeric(df_test['followers_count'],errors='coerce')

df_test['followers_count'] = df_test['followers_count'].fillna(df_test['followers_count'].median())

In [25]:
df_test['statuses_count'] = pd.to_numeric(df_test['statuses_count'],errors='coerce')

df_test['statuses_count'] = df_test['statuses_count'].fillna(df_test['statuses_count'].median())

In [26]:
df_test['friends_count'] = pd.to_numeric(df_test['friends_count'],errors='coerce')

df_test['friends_count'] = df_test['friends_count'].fillna(df_test['friends_count'].median())

In [27]:
df_test['verified']=df_test['verified'].replace("None", False)
df_test['verified']=df_test['verified'].replace("FALSE", False)
df_test['verified']=df_test['verified'].replace("TRUE", True)
# df_test['default_profile']=df_test['default_profile'].replace("None",False)
# df_test['default_profile']=df_test['default_profile'].replace("FALSE", False)
# df_test['default_profile']=df_test['default_profile'].replace("TRUE", True)

In [28]:
df_test['verified'].describe()

count       575
unique        2
top       False
freq        372
Name: verified, dtype: object

In [17]:
df_test['default_profile_image']=df_test['default_profile_image'].replace("None",False)
df_test['default_profile_image']=df_test['default_profile_image'].replace("FALSE", False)
df_test['default_profile_image']=df_test['default_profile_image'].replace("TRUE", True)

In [18]:
df_test['has_extended_profile']=df_test['has_extended_profile'].replace("None",False)
df_test['has_extended_profile']=df_test['has_extended_profile'].replace("FALSE", False)
df_test['has_extended_profile']=df_test['has_extended_profile'].replace("TRUE", True)

In [40]:
df_test.head(10)

,index,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,...,name,BotOrNot,content_classification,friend_classification,network_classification,sentiment_classification,temporal_classification,user_classification,status,bot
0,1,2281292622,2281292622,__keating,brooklyn,lgbt editor at @buzzfeed. shannon.keating@buzz...,https://t.co/QneJmYRyhj,4532.0,1309.0,111.0,...,shannon keating,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2344040251,2344040251,_callme_Dani,"Los Angeles, CA",News Curation Editor @BuzzFeedNews \nI do a lo...,NaN,298.0,780.0,10.0,...,Danielle Hopkins,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,765871267,765871267,_little_britt_,NaN,Family comes first! Also I am in love with piz...,https://t.co/E7DE1cJB7e,1045711.0,3019.0,363.0,...,Brittney Smith,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4772373433,4772373433,134k5,NaN,@BuzzFeedJapan ← @cnet_japan / DM開いてます / 取材のお願...,https://t.co/Cbguzs2PjT,467.0,522.0,18.0,...,Keigo Isashi,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1324548560,1324548560,2181chrom_bot,自分の天幕,これはFE覚醒のクロム…つまり俺がツイ廃なbotらしい。よく分からんがネタ要素しかないそうだ...,http://t.co/10Swf6luED,191.0,68.0,0.0,...,ツイ廃クロムbot,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,2561341789,2561341789,2LA1R_bot,NaN,ふれあ語をつぶやくbotです たまに中の人(ふれあ)もつぶやきます,NaN,81.0,89.0,0.0,...,ふれあ語bot ver0.2,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,347810134,347810134,3pei_bot,三河屋,■ちわーす！三河屋でーす！三郎くんには負けませんｗｗｗ■サザエさんに過去登場、三河屋さんへ勤...,http://twpf.jp/3pei_bot,2014.0,1969.0,56.0,...,三河屋三平,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,856303860,856303860,94kichi_bot,NaN,94 チャック・ウィルソンと愉快な仲間たちの笑いあり涙ありなちょこっとキチガイツイートを集め...,NaN,70.0,80.0,2.0,...,94年組bot,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,832874807754502144,832874807754502144,A3_Dekasegi_bot,ビロード駅前,シトロン「A3!出稼ぎ日誌ダヨー！みんなの出稼ぎ中のあんなことやこんなことをまとめた日誌ネ！...,https://t.co/t171JmIrjL,290.0,260.0,5.0,...,A3! 出稼ぎ日誌,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,88856792,88856792,aamir_khan,Mumbai,Actor.,https://t.co/l1dUhQjS8Y,20685240.0,9.0,20329.0,...,Aamir Khan,"{'contributors': None, 'in_reply_to_status_id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
j=0
for i in df_test.index:    
        if 'bot' in str(df_test.loc[i,'description'])or 'Bot' in str(df_test.loc[i,'description']) or 'b0t' in str(df_test.loc[i,'description']) or 'BOT' in str(df_test.loc[i,'description']) or 'B0T' in str(df_test.loc[i,'description']) or 'boT' in str(df_test.loc[i,'description']):
            #if str(df_test.loc[i,'lang'])=="en":
                df_test.loc[i,'flag1'] = True
                j=j+1
        else:
            df_test.loc[i,'flag1'] = False
print(j)

183

In [30]:
j=0
for i in df_test.index:    
        if 'bot' in str(df_test.loc[i,'screen_name'])or 'Bot' in str(df_test.loc[i,'screen_name']) or 'b0t' in str(df_test.loc[i,'screen_name']) or 'BOT' in str(df_test.loc[i,'screen_name']) or 'B0T' in str(df_test.loc[i,'screen_name']) or 'boT' in str(df_test.loc[i,'screen_name']):
            
            df_test.loc[i,'flag2'] = True
            j=j+1
        else:
            df_test.loc[i,'flag2'] = False
print(j)

207

In [31]:
j=0
for i in df_test.index:    
        if 'bot' in str(df_test.loc[i,'name'])or 'Bot' in str(df_test.loc[i,'name']) or 'b0t' in str(df_test.loc[i,'name']) or 'BOT' in str(df_test.loc[i,'name']) or 'B0T' in str(df_test.loc[i,'name']) or 'boT' in str(df_test.loc[i,'name']):
            
            df_test.loc[i,'flag3'] = True
            j=j+1
        else:
            df_test.loc[i,'flag3'] = False
print(j)

159

In [44]:
clf = RandomForestClassifier(n_jobs=2)
clf.fit(df[features], df['bot'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [24]:
df_test.head(20)

,index,id,id_str,screen_name,location,description,url,followers_count,friends_count,listedcount,...,friend_classification,network_classification,sentiment_classification,temporal_classification,user_classification,status,bot,flag1,flag2,flag3
0,1,2281292622,2281292622,__keating,brooklyn,lgbt editor at @buzzfeed. shannon.keating@buzz...,https://t.co/QneJmYRyhj,4532.0,1309.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
1,2,2344040251,2344040251,_callme_Dani,"Los Angeles, CA",News Curation Editor @BuzzFeedNews \nI do a lo...,NaN,298.0,780.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
2,3,765871267,765871267,_little_britt_,NaN,Family comes first! Also I am in love with piz...,https://t.co/E7DE1cJB7e,1045711.0,3019.0,363.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
3,4,4772373433,4772373433,134k5,NaN,@BuzzFeedJapan ← @cnet_japan / DM開いてます / 取材のお願...,https://t.co/Cbguzs2PjT,467.0,522.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4,5,1324548560,1324548560,2181chrom_bot,自分の天幕,これはFE覚醒のクロム…つまり俺がツイ廃なbotらしい。よく分からんがネタ要素しかないそうだ...,http://t.co/10Swf6luED,191.0,68.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True
5,6,2561341789,2561341789,2LA1R_bot,NaN,ふれあ語をつぶやくbotです たまに中の人(ふれあ)もつぶやきます,NaN,81.0,89.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True
6,7,347810134,347810134,3pei_bot,三河屋,■ちわーす！三河屋でーす！三郎くんには負けませんｗｗｗ■サザエさんに過去登場、三河屋さんへ勤...,http://twpf.jp/3pei_bot,2014.0,1969.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False
7,8,856303860,856303860,94kichi_bot,NaN,94 チャック・ウィルソンと愉快な仲間たちの笑いあり涙ありなちょこっとキチガイツイートを集め...,NaN,70.0,80.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True
8,9,832874807754502144,832874807754502144,A3_Dekasegi_bot,ビロード駅前,シトロン「A3!出稼ぎ日誌ダヨー！みんなの出稼ぎ中のあんなことやこんなことをまとめた日誌ネ！...,https://t.co/t171JmIrjL,290.0,260.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False
9,10,88856792,88856792,aamir_khan,Mumbai,Actor.,https://t.co/l1dUhQjS8Y,20685240.0,9.0,20329.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
10,11,713556609784479744,713556609784479744,AceWallpaperBot,NaN,Posts a [SFW] wallpaper every 30 minutes. Ever...,https://t.co/tuq9iPhc0Z,20851.0,8.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True
11,12,1566746503,1566746503,acormier_bzfd,"New York, NY",Investigative Reporter-Editor @buzzfeed. Forme...,https://t.co/iiAufe34NG,1498.0,2049.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
12,13,90420314,90420314,ActuallyNPH,Manhattanland,"I dig variety acts, Pixar, puppets, prestidigi...",https://t.co/c8ibVF0Lfq,26520297.0,93.0,60701.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
13,14,184910040,184910040,Adele,London,https://t.co/5Vf55N5xFe,https://t.co/5Vf55N5xFe,28035314.0,157.0,33032.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
14,15,157690631,157690631,aflores,Los Angeles,Latino affairs and breaking news reporter for ...,http://t.co/ykLlu4DCdC,5287.0,2563.0,234.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
15,16,42420346,42420346,agnezmo,Los Angeles,DREAM BELIEVE & MAKE IT HAPPEN! Instagram: @ag...,https://t.co/PYhVmN5FYH,16394932.0,1071.0,10849.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
16,17,42382447,42382447,Agostinozoida,NaN,NaN,https://t.co/2gdWyQjNq4,963.0,333.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
17,18,43993280,43993280,AhmedBharoocha,NaN,I forget to tweet,https://t.co/iM3lj0uBHg,5267.0,2409.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
18,19,2305236733,2305236733,aho_levi_bot,teamリヴァイ,YDK。botシステム外部レンタルから自作に乗り換えました。呼ぶとヒョッコリ現れます。モノを...,NaN,441.0,422.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False
19,20,742793690838642688,742793690838642688,aiomacbot,NaN,A simple all-in-one bot for the Mac,https://t.co/cR0QCvj4cu,1656.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True

In [32]:
result=pd.DataFrame(df_test['id'])
result.insert(1,'bot',0)
rfresult=clf.predict(df_test[newf])

result['bot']=rfresult
result=result.astype(int)
pd.DataFrame(result).to_csv('result12.csv',sep=',',index=False)

In [19]:
# print(len(df_test))
# j=0
# changed =0
# for i in df_test['description']:
#      if 'bot' in str(i) or 'Bot' in str(i) or 'b0t' in str(i):
#         if rfresult[j]!=1:
#             rfresult[j]=1
#             print(j)
#             print(i)
#             print('********************')
#             changed=changed+1
#     j=j+1
# #print (np.mean(rfresult==test['bot']))
# print(changed)

In [46]:
# j=0
# changed =0
# for i in df_test['screen_name']:
#     if 'bot' in i or 'Bot' in i or 'b0t' in i or 'BOT' in i:
#         if rfresult[j]!=1:
#             rfresult[j]=1
            
#             print(j)
#             changed=changed+1
#     j=j+1
# #print (np.mean(pred==test['bot']))
# print(changed)